---
title: "My title"
subtitle: "My subtitle if needed"
author: 
  - First author
  - Another author
thanks: "Code and data are available at: LINK."
date: "`r format(Sys.time(), '%d %B %Y')`"
abstract: "First sentence. Second sentence. Third sentence. Fourth sentence."
output:
  bookdown::pdf_document2
toc: FALSE
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(haven)
library(dplyr)
library(readr)
library(knitr)
library(ggplot2)
library(here)
library(tinytex)
library(kableExtra)
```



# Data------------Macro_data
```{r, include=FALSE}
#load  data
Macro_data
```

# Graph------------Macro_data graph 1.female
```{r grade, fig.cap="female: Micro grade vs Mean nomicro gpa", fig.weight=3.3, fig.Weight=2.5, echo=FALSE, warning=FALSE, message=FALSE}
female_macro <- filter(Macro_data,female == "1")

ggplot(female_macro, aes(x = mean_gpa_nomicro, y = micro_grade , color = macro_econ == 1)) +
geom_point() +
  labs(color = "macro_econ",
       x = "Mean Gpa",
       y = "Macro grade",
       title = "Micro grade vs Mean nomicro gpa--Feale")+
  geom_abline(intercept =-0.4 , slope = 1.1)
```
# Graph------------Macro_data graph 1.male
```{r grade, fig.cap="male: Micro grade vs Mean nomicro gpa", fig.height=3.3, fig.height=2.5, echo=FALSE, warning=FALSE, message=FALSE}
male_macro <- filter(Macro_data,female == "0")

ggplot(male_macro, aes(x = mean_gpa_nomicro, y = micro_grade , color = macro_econ == 1)) +
geom_point() +
  labs(color = "macro_econ",
       x = "Mean Gpa",
       y = "Macro grade",
       title = "Micro grade vs Mean nomicro gpa--Male")+
  geom_abline(intercept =0 , slope = 1)
       
```


# Data------------Int_micro_data
```{r, include=FALSE}
#load  data
Int_micro_data
```


# Graph------------Int_micro_data graph 1.female
```{r grade, fig.cap="female: Macro grade vs Mean nomacro gpa", fig.height=3.3, fig.height=2.5, echo=FALSE, warning=FALSE, message=FALSE}
female_Int_micro_data <- filter(Int_micro_data,female == "1")

ggplot(female_Int_micro_data, aes(x = mean_gpa_nomacro, y = macro_grade , color = int_micro == 1)) +
geom_point() +
  labs(color = "int_micro",
       x = "Mean Gpa",
       y = "Macro grade",
       title = "Macro grade vs Mean nomacro gpa--Female")+
  geom_abline(intercept =-1 , slope = 1.25)

```

# Graph------------Int_micro_data graph 2.Male
```{r grade, fig.cap="Male: Macro grade vs Mean nomacro gpa", fig.height=3.3, fig.height=2.5, echo=FALSE, warning=FALSE, message=FALSE}
male_Int_micro_data <- filter(Int_micro_data,female == "0")

ggplot(male_Int_micro_data, aes(x = mean_gpa_no_macro, y = macro_grade , color = int_micro == 1)) +
geom_point() +
  labs(color = "int_micro",
       x = "Mean Gpa",
       y = "Macro grade",
       title = "Macro grade vs Mean nomacro gpa--Male") + geom_abline(intercept =-0.4 , slope = 1.1)

```



# 3. Table----Macro table
```{r tab, fig.cap="", echo=FALSE}

Macro_table_data <- group_by(Macro_data, female)
summarise(Macro_table_data, Micro_grade = mean(micro_grade), relative_grade = mean(micro_relative_grade) ) %>% mutate_if(is.numeric, round, digits = 2) -> Macro_table_data2
knitr::kable(Macro_table_data2, 
             caption = "Mean",
             col.names = c("Gender", "Mean grade", "Mean Relative Grade"),
             align = c("c", "c", "c")) %>% kable_styling(latex_options = "HOLD_position")%>%
add_footnote("0 = Male, 1 = Female", notation="symbol")

```

# 3. Table----Int Micro table
```{r tab, fig.cap="", echo=FALSE}

Int_micro_table_data <- group_by(Int_micro_data, female)
summarise(Int_micro_table_data, Macro_grade = mean(macro_grade), relative_grade = mean(macro_relative_grade) ) %>% mutate_if(is.numeric, round, digits = 2) -> Int_micro_table_data2
knitr::kable(Int_micro_table_data2, 
             caption = "Mean",
             col.names = c("Gender", "Mean grade", "Mean Relative Grade"),
             align = c("c", "c", "c")) %>% kable_styling(latex_options = "HOLD_position")%>%
add_footnote("0 = Male, 1 = Female", notation="symbol")

```

